### ISSUE TITLE
flag support in comment parser. extension on #5

### ISSUE THREAD

**Issue by steviestickman** [R2D2-2019/r2d2-python-build#30]
the Command Line Interface (CLI) have requested that the comment parser (#5) also support flags.
```c++
/*
 * @cond CLI COMMAND @endcond a short description
 */
class frame_flag_test{}
```
should result in something like
```python
class flag_test(Frame):
    description = "a short description"
```
see https://github.com/R2D2-2019/r2d2-python-build/compare/release...R2D2-2019:feature-cli-command-frame-parser for the proposal from @Timvdijk and @jasperdewinther

**Comment by Timvdijk** [comment]
implemented in #31
