### ISSUE TITLE
invalid frame name syntax

### ISSUE THREAD

**Issue by Timvdijk** [R2D2-2019/r2d2-python-build#46]
The current frames.py generates a `SyntaxError`, on line 74 (and probably also on lines after this):
![image](https://user-images.githubusercontent.com/31770296/58044662-a356aa00-7b40-11e9-9591-d5d2676b3690.png)

This is caused by the `[]`

**Comment by steviestickman** [comment]
resolved in the release branch, tonight will be released to master
