### ISSUE TITLE
String pack support

### ISSUE THREAD

**Issue by Timvdijk** [R2D2-2019/r2d2-python-build#47]
When trying to `set_data` of a struct which contains one or more string members, I get the following error: `struct.error: char format requires a bytes object of length 1`
This means it is trying to pack the string to a single char, which is not what we want.

For example for `FrameUiCommand`, this fixes the issue:
![image](https://user-images.githubusercontent.com/31770296/58044968-7787f400-7b41-11e9-855e-589407c023bd.png)
This just solves the packing issue, I do not know if this works correctly with unpacking on the other end.

**Comment by steviestickman** [comment]
noted, this will be resolved by #51
