### ISSUE TITLE
Don't print anymore

### ISSUE THREAD

**Issue by florianhumblot** [R2D2-2019/r2d2-python-build#67]
If a module runs on the server, it's output will not be visible to the operators if they used `print`.

Proposed solution:

Have the modules use the `logging` module, which has to be setup to log to `$module_name.log`. This way operators will be able to read the log with their output which will help them debug their services.

**Comment by LRstudentHU** [comment]
Is there a way stdout could be rerouted? There's probably a service that could show it on a web interface or something

**Comment by florianhumblot** [comment]
stdout could be routed to a logging file, but that doesn't always function correctly, and considering that the python-build environment already uses the logging module, I think the best way to handle this would be to set the target output of that module to a predetermined logfile
